object Versions {

    const val kotlin = "1.5.31"
    const val buildTools = "7.0.3"
    const val navigation = "2.4.0-beta02"
    const val hilt = "2.40.1"
    const val crashlytics = "2.7.1"
    const val ktLint = "10.0.0"
    const val material = "1.4.0"
    const val compose = "1.1.0-beta03"
    const val composeActivity = "1.4.0"
    const val composeAccompanist = "0.21.3-beta"
    const val composeCoil = "1.3.1"
    const val hiltNavigation = "1.0.0-alpha03"
    const val retrofit = "2.9.0"
    const val moshi = "1.12.0"
    const val interceptor = "4.9.1"
    const val coroutines = "1.5.1"

    // testing
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.3"
    const val espresso = "3.4.0"
    const val barista = "3.7.0"
    const val mockk = "1.10.6"
    const val mockito = "3.3.3"
    const val nhaarman = "2.0.0-RC3"
    const val jUnitRule = "1.3.0"
    const val coreTesting = "2.1.0"
    const val liveDataTesting = "1.2.0"
}
